plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = mod_version
group = 'com.com.yourname'

repositories {
    mavenLocal()
}

base {
    archivesName = 'create-guardian-shooter'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {

    version = project.neo_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    runs {
        client {
            client()

            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }

        data {
            data()
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        // applies to all the run configs above
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {

        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}


sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { url = "https://maven.createmod.net" }  // уже есть
    maven { url = "https://maven.realrobotix.me/createbigcannons" } // для CBC
}

dependencies {
    additionalRuntimeClasspath fileTree(dir: 'libs', include: ['create-1.21.1-6.0.10.jar'])
    additionalRuntimeClasspath fileTree(dir: 'libs', include: ['createbigcannons-5.11.3-*.jar'])
    additionalRuntimeClasspath fileTree(dir: 'libs', include: ['sable-neoforge-1.21.1-1.1.3.jar'])
    compileOnly fileTree(dir: 'libs', include: ['create-aeronautics-bundled-*.jar'])
    compileOnly fileTree(dir: 'libs', include: ['create-1.21.1-6.0.10.jar'])
    compileOnly fileTree(dir: 'libs', include: ['createbigcannons-*.jar'])

    compileOnly fileTree(dir: 'libs', include: ['sable-neoforge-1.21.1-*.jar'])
    // Ponder — только для компиляции, точная версия из .pom
    compileOnly "net.createmod.ponder:ponder-neoforge:1.0.82+mc1.21.1"
    compileOnly fileTree(dir: 'libs', include: ['sable-companion-common-*.jar'])
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version_range,
                             loader_version_range   : loader_version_range,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}


sourceSets.main.resources.srcDir generateModMetadata

neoForge.ideSyncTask generateModMetadata


publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}


idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
